---
title: What I Find Interesting
subtitle: Podcasts, Comics, Blogs and Essays
excerpt: Podcasts, Comics, Blogs and Essays
author: Harshvardhan
date: '2021-06-19'
slug: []
categories:
  - life
  - social
  - thoughts
tags: []
---

### Podcasts

-   **TED:** TED's novelty is not a secret. Watch it; you will indeed find an exciting idea.

-   **Talks At Google:** Each time, they invite a great person to share their ideas about unconventional topics. They are pretty brave --- not shying away from calling people who are critical about Google's activities. You may like to start with Yuval Noah Harari's episode.

-   **Planet Money:** This is an easy listen with unique insights with practical economics lessons and examples.

-   **Linear Digressions:** All about machine learning and statistics.

### Comics

-   **Calvin and Hobbes:** Calvin's view of the world represents an exciting, marvellous vision of the world around him. Hobbes is the perfect companion. Their journey is like two adults taking a world tour in children's body.

### Industry Research Blogs

-   [Reserach at Spotify](https://research.atspotify.com/blog/)

-   [Facebook's General Blog](https://www.facebook.com/formedia/blog)

-   [Research at Facebook](https://research.fb.com/blog/)

-   [The Unofficial Google Data Science Blog](https://www.unofficialgoogledatascience.com/)

-   [Google AI Blog](https://ai.googleblog.com/)

-   [Netflix Tech Blog](https://netflixtechblog.com/)

-   [Netflix Research](https://research.netflix.com/articles)

-   [Netflix Blog](https://about.netflix.com/en/newsroom)

### Personal Blogs / Essays

-   [Vicki Boykis](http://vickiboykis.com/)

-   [Ximena Vengoechea](https://www.ximenavengoechea.com/)

-   [Who is 'Red'? - Red Russak](http://redrussak.com/)

-   [Debarghya Das](http://debarghyadas.com/)

-   [Yihui Xie \| 谢益辉](https://yihui.org/)

-   [Alison Hill](https://www.apreshill.com/)

-   [Jacqueline Nolis](https://jnolis.com/)

-   [Home \| The Tidy Trekker](https://www.thetidytrekker.com/)

-   [ijeamaka anyene](https://ijeamaka-anyene.netlify.app/index.html)

-   [Brendan Cullen](https://bcullen.rbind.io/)

-   [Allison Horst](https://www.allisonhorst.com/)

-   [Stephanie Kirmer](https://skirmer.github.io/)

-   [Cédric Scherer - Cédric Scherer](https://www.cedricscherer.com/)

-   [Amber Thomas Data Portfolio & Blog \| Amber Thomas Data Portfolio & Blog](https://amber.rbind.io/)

-   [Jesse Mostipak](https://www.jessemaegan.com/)

-   [Sara A. Stoudt, PhD](https://sastoudt.github.io/)

-   [Hooked on Data, Emily Robinson](https://hookedondata.org/)

-   [Kara Woo](https://karawoo.com/)

-   [Greg Wilson](https://third-bit.com)

-   [Haystacks by Caitlin Hudon](https://www.caitlinhudon.com/)

-   [Little Miss Data](https://www.littlemissdata.com/)

-   [Cogito, Ergo Sumana](https://harihareswara.net/)

-   [danluu.com](https://danluu.com)

-   [Paul Graham](http://www.paulgraham.com/articles.html)

-   [Kevin Kelly](https://kk.org/thetechnium/)

-   [Vicki Boykis](https://vickiboykis.com/essays/)

-   [Greg Wilson](https://third-bit.com/blog/)

-   [Ben Kuhn](https://www.benkuhn.net)

-   [Nate Soares](https://mindingourway.com/)

-   [Sam Altman](https://blog.samaltman.com)


## Data Science

### Advice Blogs

-   [Advice to aspiring data scientists: start a blog](http://varianceexplained.org/r/start-blog/)

-   [Non-Academic Careers for Astronomers and Physicists](https://speakerdeck.com/juliasilge/non-academic-careers-for-astronomers-and-physicists)

-   Concept of Digital Garden [Vicki Boykis \| Your public garden \| RStudio::rconf, Youtube](https://www.youtube.com/watch?v=E5ERSfydB30)

-   [How Do You Create A Phenomenal Job Talk?](https://bettylai.com/blog/post/phenomenal-job-talks)

-   [Amelia McNamara on Twitter: ""Things that are still on your computer are approximately useless." -\@drob #eUSR #eUSR2017](https://twitter.com/AmeliaMN/status/926509282874585089)<https://t.co/nS3IBiRHBn%22>[/ Twitter](https://twitter.com/AmeliaMN/status/926509282874585089)

### Industry Blogs

-   Facebook: <https://research.facebook.com/blog/>

-   Netflix: [https://netflixtechblog.com/](https://netflixtechblog.com/?gi=343beb007429)

-   Google: <https://ai.googleblog.com/>, <https://blog.google/technology/research/>

-   Spotify: <https://engineering.atspotify.com/>, <https://research.atspotify.com/blog/>

### Technical Ideas

-   [Transfer Learning - Machine Learning's Next Frontier](https://ruder.io/transfer-learning/)

-   [Algorithm Archive · Arcane Algorithm Archive, Encyclopedia of algorithms](https://www.algorithm-archive.org/)

### Programming

-   [Advent of Code](https://adventofcode.com/) is a programming challenge.

-   [Project Euler](https://projecteuler.net/) is similar.

### R

-   [My Opinion on R's Upcoming Pipe](https://www.r-bloggers.com/2020/12/my-opinion-on-rs-upcoming-pipe/)

-   Why performance is not the issue in R [Why R? 2020 Discussion Panel - Performance in R, Youtube Video](https://www.youtube.com/watch?v=uiEhmKN1RJo)

-   Quanteda [Why R? 2020 \| Ken Benoit - Why you should stop using other text mining packages and embrace quanteda](https://www.youtube.com/watch?v=9hEvGBu3cnI)

-   [Visualising distributions with raincloud plots and how to create them with ggplot2](https://www.cedricscherer.com/2021/06/06/visualizing-distributions-with-raincloud-plots-and-how-to-create-them-with-ggplot2/)

-   [An R User's Note on Learning Python](https://rpubs.com/MenaWANG/LearningPython-Automation1)

-   [Jitter in boxplots to show distribution](https://stackoverflow.com/questions/70227169/how-to-plot-the-points-position-correspond-to-the-boxplots)

-   [Using databases with Shiny](https://emilyriederer.netlify.app/post/shiny-db/)

-   [Martin Wattenberg On Visualizing Large Textual Data \| FlowingData](https://flowingdata.com/2008/07/21/martin-wattenberg-on-visualizing-large-textual-data/)

-   [R as a First Programming Language](https://seankross.com/2019/10/27/R-as-a-First-Programming-Language.html)

-   [Do We Need Object Oriented Programming in Data Science? \| by Rose Day \| Oct, 2020 \| Towards Data Science](https://towardsdatascience.com/do-we-need-object-orientated-programming-in-data-science-b4a7c431644f)

------------------------------------------------------------------------

## Other Good Reads

### Articles

-   [Tech is improving at an exponential rate. Here's what that means for society](https://www.morningbrew.com/emerging-tech/stories/2021/11/24/tech-is-improving-at-an-exponential-rate-here-s-what-that-means-for-society?utm_campaign=mb&utm_medium=newsletter&utm_source=morning_brew&mid=db18db43828180889e38a0bc0e4ac362&uid=MifcoVe3xqQeEeaWE3US3gLv)

-   [A free introduction to quantum computing and quantum mechanics, A New Kind of Book](https://quantum.country)

-   [Maps, Simpson's Paradox, Sienfield, and what not.](https://michaelnielsen.org/reinventing_explanation/index.html)

-   [Here's Why Movie Dialogue Has Gotten More Difficult To Understand (And Three Ways To Fix It)](https://www.slashfilm.com/673162/heres-why-movie-dialogue-has-gotten-more-difficult-to-understand-and-three-ways-to-fix-it/?s=09)

-   [Encyclopedic Knowledge, Then vs. Now - The New York Times](https://www.nytimes.com/2009/05/03/business/03digi.html)

-   [12ft \| Microsoft Encarta Dies After Long Battle With Wikipedia - The New York Times](https://12ft.io/proxy?q=http://bits.blogs.nytimes.com/2009/03/30/microsoft-encarta-dies-after-long-battle-with-wikipedia)

-   [Early Civilizations Had It All Figured Out \| The New Yorker](https://www.newyorker.com/magazine/2021/11/08/early-civilizations-had-it-all-figured-out-the-dawn-of-everything)

-   [The Surprisingly Big Business of Library E-books \| The New Yorker](https://www.newyorker.com/news/annals-of-communications/an-app-called-libby-and-the-surprisingly-big-business-of-library-e-books)

-   [Martha's Rules for Group Decision Making](https://third-bit.com/2019/06/13/marthas-rules/)

-   [Greg Wilson's Ideas](https://third-bit.com/ideas/)

-   [Searching for Susy Thunder](https://www.theverge.com/c/22889425/susy-thunder-headley-hackers-phone-phreakers-claire-evans)

### Twitter Threads

-   [Jessica Price on Twitter: "Since I've gotten a lot of "why won't you debate me?" in response to talking about tabletop/geekdom's problems, I'll tell you." / Twitter](https://twitter.com/Delafina777/status/839754651230601216)

-   [Naval on Twitter: "How to Get Rich (without getting lucky):" / Twitter](https://twitter.com/naval/status/1002103360646823936)

### Blogs (Maths)

-   [The Mathematics of Mind-Time](https://getpocket.com/explore/item/the-mathematics-of-mind-time)

-   A Brilliant Biography about about Gödel [Kurt Gödel's Brilliant Madness](https://www.privatdozent.co/p/kurt-godels-brilliant-madness)

-   How to imagine four or more dimensional objects [Intuitive crutches for higher dimensional thinking](https://mathoverflow.net/questions/25983/intuitive-crutches-for-higher-dimensional-thinking)

### Print

[***Email me***](mailto:harsh@harsh17.in) ***if you need a scanned copy of these items (for personal use only)***

-   Chapter on Mental Health in [Bitwise: A Life in Code](https://www.goodreads.com/book/show/35794819-bitwise)

-   [Playboy Interview: Steven Jobs, The best interview I've ever read by a margin](https://allaboutstevejobs.com/verbatim/interviews/playboy_1985)

-   It's Happened Again by Oscar Schwartz. Wired. Print: February 2022

-   The Big Inhale by Vince Beiser. Wired. Print: February 2022

------------------------------------------------------------------------

## YouTube

-   [How To Speak by Patrick Winston, MIT OCW](https://www.youtube.com/watch?v=Unzc731iCUY)

-   [NASA \| Thermonuclear Art -- The Sun In Ultra-HD (4K)](https://www.youtube.com/watch?v=6tmbeLTHC_0)

-   [A Buddhist asks Sadhguru a Puzzling Question #Vipassana](https://www.youtube.com/watch?v=6OdKZRnmRQ0)

-   [Most People Don't Know How Bikes Work](https://www.youtube.com/watch?v=9cNmUNHSBac)

-   [Joe Rogan Experience #1309 - Naval Ravikant - YouTube](https://www.youtube.com/watch?v=3qHkcs3kG44)

------------------------------------------------------------------------

## Cool Apps

-   Chrome [Tab Link Copier - Chrome Web Store](https://chrome.google.com/webstore/detail/tab-link-copier/ijkpnaifgolhlcfhcfamddnlnfjpjaji/related?hl=en)

-   Mac [jaywcjlove/awesome-mac:  Now we have become very big, Different from the original idea. Collect premium software in various categories.](https://github.com/jaywcjlove/awesome-mac)

-   Mac [serhii-londar/open-source-mac-os-apps: 🚀 Awesome list of open source applications for macOS.](https://github.com/serhii-londar/open-source-mac-os-apps)<https://t.me/s/opensourcemacosapps>

------------------------------------------------------------------------

## Todoist Blogs

-   Benefits of Walking Meetings [Can Walking Meetings Lead to Healthier Lives?](https://blog.doist.com/remote-work-meetings/)

-   [60+ Resources for Students Who Want to Stay Productive](https://blog.doist.com/60-resources-students-stay-productive/)

-   [Hedonic Adaptation: Why we're never satisfied with what we've already accomplished](https://blog.doist.com/hedonic-adaptation-comic/)

-   [The Mere Urgency Effect](https://blog.doist.com/mere-urgency-effect-comic/)

-   [The Planning Fallacy: Why We're Terrible at Setting Realistic Deadlines](https://blog.doist.com/planning-fallacy-comic/)

-   [The Zeigarnik Effect: Why Unfinished Work Follows Us Home](https://blog.doist.com/zeigarnik-effect-comic/)

-   [Complexity Bias: Why We Overcomplicate Our Lives](https://blog.doist.com/complexity-bias-comic/)

-   [The Two-Minute Rule: Stop Procrastinating With This Simple Trick](https://blog.doist.com/two-minute-rule/)

-   [The Life-Changing Magic of Tidying Up Your To-Do List](https://blog.doist.com/life-changing-magic-tidying-todoist/)

-   [The Sunk Cost Fallacy & Your Productivity - Doist Blog](https://blog.doist.com/sunk-cost-fallacy-comic/)

------------------------------------------------------------------------


