---
title: Rules for Life
subtitle: Constants, not variables
summary: Constants, not variables
author: Harshvardhan
date: '2022-02-18'
slug: rules
categories:
  - thoughts
tags: []
---

1.  If it takes less than 2 mins to do, do it now.
2.  [Do things, tell people.](http://carl.flax.ie/dothingstellpeople.html)
3.  Build a model of everything. The model doesn't have to be perfect but just better than a coin toss. Absorb the fact that you could be 100% wrong.
4.  Choose what to believe in. There are good ideas in bad people's brain; bad ideas in good people brain. As Gandhi said, *hate the sin not the sinner*.
5.  Become the best in the world at what you do. Keep redefining what you do until this is true.
    -   Don't be the best. Be the only.
6.  Work as hard as you can. Even though who you work with and what you work on are more important than how hard you work.
7.  [Always demand a deadline.](https://kk.org/thetechnium/68-bits-of-unsolicited-advice/) A deadline weeds out the extraneous and the ordinary. It prevents you from trying to make it perfect, so you have to make it different. Different is better.
8.  Promptness is a sign of respect.
