---
title: Bullets of Wisdom
author: Harsh
date: '2022-10-07'
slug: wise
categories:
  - life
  - thoughts
  - live
tags: []
draft: true
---

Life is short for learning from your own mistakes; you need to play catch-up with people who tried new things. Most people do not document their learnings. The rare culturati group that notes their understandings in an essay easily trumps the large group, which keeps their learnings to themselves.

I have read many interesting essays. Some of them stuck with me --- like fingers working with super glue. I revisit them often. When I reread them, I often see myself clinging to an awfully good section. In this live post, I will share some of those good nuggets.

> Everything that needs to be said has already been said. But since no one was listening, everything must be said again.
>
> --- André Gide

## Life is Short

Paul Graham, <http://www.paulgraham.com/vb.html>

Paul Graham is one of my favourite essayists. I've read a lot of his essays. This one in particular frequently makes me rethink about what is important in life and what is not. Eliminate the unnecessary, focus on the required.

> Ok, so life actually is short. Does it make any difference to know that?
>
> It has for me. It means arguments of the form "Life is too short for x" have great force. It's not just a figure of speech to say that life is too short for something. It's not just a synonym for annoying. If you find yourself thinking that life is too short for something, you should try to eliminate it if you can.
>
> When I ask myself what I've found life is too short for, the word that pops into my head is "bullshit." I realize that answer is somewhat tautological. It's almost the definition of bullshit that it's the stuff that life is too short for. And yet bullshit does have a distinctive character. There's something fake about it. It's the junk food of experience.
>
> But while some amount of bullshit is inevitably forced on you, the bullshit that sneaks into your life by tricking you is no one's fault but your own. And yet the bullshit you choose may be harder to eliminate than the bullshit that's forced on you. Things that lure you into wasting your time have to be really good at tricking you. An example that will be familiar to a lot of people is arguing online. When someone contradicts you, they're in a sense attacking you. Sometimes pretty overtly. Your instinct when attacked is to defend yourself. But like a lot of instincts, this one wasn't designed for the world we now live in. Counterintuitive as it feels, it's better most of the time not to defend yourself. Otherwise these people are literally taking your life.

## There is no speed limit

Derek Sivers, <https://sive.rs/kimo>

The "defined" pace exists so that anyone could do it. If you are driven and realise there is no speed limit, you can travel faster, hence further in life.

> After a one-minute welcome, we were sitting at the piano, analyzing the sheet music for a jazz standard. He was quickly explaining the chords based on the diatonic scale --- how the dissonance of the tri-tone in the 5-chord with the flat-7 is what makes it want to resolve to the 1. Within a minute, he started quizzing me.
>
> "If the 5-chord with the flat-7 has that tri-tone, then so does another flat-7 chord. Which one?"
>
> "Uh... the flat-2 chord?"
>
> "Right! So that's a substitute chord. Any flat-7 chord can be substituted with the other flat-7 that shares the same tri-tone. So reharmonize all the chords you can in this chart. Go."
>
> **The pace was intense, and I loved it. Finally, someone was challenging me --- keeping me in over my head --- encouraging and expecting me to pull myself up quickly. I was learning so fast, it felt like the adrenaline rush you get while playing a video game. He tossed every fact at me and made me prove that I got it.**

## Do things, tell people.

Carl Lange, <http://carl.flax.ie/dothingstellpeople.html>

> These are the only things you need to do to be successful. You can get away with just doing one of the two, but that's rare, and usually someone else is doing the other part for you.
>
> ...
>
> **Then make something that you can talk about. Make something cool. Something interesting. Spend time on it. Go crazy. Even if it's the least useful thing you've ever made, if you can talk about it, make it. This part is easy, because you're doing something you think is cool, and interesting, and if it's useless, great, because you won't need to support it much either!**
>
> ...
>
> You would not believe how much opportunity is out there for those who do things and tell people. It's how you travel the entreprenurial landscape. You do something interesting and you tell everyone about it.

## You and Your Research

Richard Hamming, <http://www.paulgraham.com/hamming.html>

This is probably the gem of this list, especially at this point of my life when I'm trying to find what is a good research. If you're serious about your career, you should check it out. You can also watch the talk here: <https://www.youtube.com/>[^1]

[^1]: The content in video is slightly different from the essay. Like Hamming says in the video, he has delivered this talk at many places by various names.

### Luck

> Let me start not logically, but psychologically. I find that the major objection is that people think great science is done by luck. It's all a matter of luck. Well, consider Einstein. Note how many different things he did that were good. Was it all luck? Wasn't it a little too repetitive? Consider Shannon. He didn't do just information theory. Several years before, he did some other good things and some which are still locked up in the security of cryptography. He did many good things.
>
> ...
>
> So yes, it is luck. The particular thing you do is luck, but that you do something is not.
>
> For example, when I came to Bell Labs, I shared an office for a while with Shannon. At the same time he was doing information theory, I was doing coding theory. It is suspicious that the two of us did it at the same place and at the same time --- it was in the atmosphere. And you can say, "Yes, it was luck." On the other hand you can say, "But why of all the people in Bell Labs then were those the two who did it?" Yes, it is partly luck, and partly it is the prepared mind; but "partly" is the other thing I'm going to talk about.

### Ardent Curiousity

> One of the characteristics you see, and many people have it including great scientists, is that usually when they were young they had independent thoughts and had the courage to pursue them. For example, Einstein, somewhere around 12 or 14, asked himself the question, "What would a light wave look like if I went with the velocity of light to look at it?"
>
> ...
>
> **One of the characteristics of successful scientists is having courage. Once you get your courage up and believe that you can do important problems, then you can. If you think you can't, almost surely you are not going to.** Courage is one of the things that Shannon had supremely. You have only to think of his major theorem. He wants to create a method of coding, but he doesn't know what to do so he makes a random code. Then he is stuck. And then he asks the impossible question, "What would the average random code do?" He then proves that the average code is arbitrarily good, and that therefore there must be at least one good code. Who but a man of infinite courage could have dared to think those thoughts? That is the characteristic of great scientists; they have courage. They will go forward under incredible circumstances; they think and continue to think.

### **The best time to plant a tree was 20 years ago.** **The second best time is now.**

> Age is another factor which the physicists particularly worry about. They always are saying that you have got to do it when you are young or you will never do it. Einstein did things very early, and all the quantum mechanic fellows were disgustingly young when they did their best work. Most mathematicians, theoretical physicists, and astrophysicists do what we consider their best work when they are young.
>
> ...
>
> You may find yourself as I saw Brattain when he got a Nobel Prize. The day the prize was announced we all assembled in Arnold Auditorium; all three winners got up and made speeches. The third one, Brattain, practically with tears in his eyes, said, "I know about this Nobel-Prize effect and I am not going to let it affect me; I am going to remain good old Walter Brattain." Well I said to myself, "That is nice." But in a few weeks I saw it was affecting him. Now he could only work on great problems.

### Turning problem on it's head

> I think that if you look carefully you will see that often the great scientists, by turning the problem around a bit, changed a defect to an asset. For example, many scientists when they found they couldn't do a problem finally began to study why not. They then turned it around the other way and said, "But of course, this is what it is" and got an important result. So ideal working conditions are very strange. The ones you want aren't always the best ones for you.

### Being driven

> I worked for ten years with John Tukey at Bell Labs. He had tremendous drive. One day about three or four years after I joined, I discovered that John Tukey was slightly younger than I was. John was a genius and I clearly was not. Well I went storming into Bode's office and said, **"How can anybody my age know as much as John Tukey does?"** He leaned back in his chair, put his hands behind his head, grinned slightly, and said, **"You would be surprised Hamming, how much you would know if you worked as hard as he did that many years."** I simply slunk out of the office!
>
> ...
>
> What Bode was saying was this: **Knowledge and productivity are like compound interest**. Given two people of approximately the same ability and one person who works ten percent more than the other, the latter will more than twice outproduce the former. The more you know, the more you learn; the more you learn, the more you can do; the more you can do, the more the opportunity --- it is very much like compound interest. I don't want to give you a rate, but it is a very high rate. Given two people with exactly the same ability, the one person who manages day in and day out to get in one more hour of thinking will be tremendously more productive over a lifetime.

### What you know could be wrong

> There's another trait on the side which I want to talk about; that trait is ambiguity. It took me a while to discover its importance. **Most people like to believe something is or is not true. Great scientists tolerate ambiguity very well.** They believe the theory enough to go ahead; they doubt it enough to notice the errors and faults so they can step forward and create the new replacement theory. If you believe too much you'll never notice the flaws; if you doubt too much you won't get started. It requires a lovely balance.
>
> ...
>
> **Darwin writes in his autobiography that he found it necessary to write down every piece of evidence which appeared to contradict his beliefs because otherwise they would disappear from his mind.** When you find apparent flaws you've got to be sensitive and keep track of those things, and keep an eye out for how they can be explained or how the theory can be changed to fit them. Those are often the great contributions.

### Creativity
