---
title: Artificial Intelligence and Data Sciences in Real-world Business
author: Harshvardhan
slug: data-sciences-in-real-world
categories:
  - ai
  - coding
  - HP
  - ML
  - statistics
tags: []
subtitle: "A quick rundown of my doctoral research presented at the BA Forum 2023"
summary: "A quick rundown of my doctoral research presented at the BA Forum 2023"
date: '2023-09-07T13:00:00Z'
event: 'Business Analytics Forum'
location: "University of Tennessee, Knoxville"
---

In a recent talk, I discussed my PhD research which aims to leverage AI to solve two business problems - forecasting print demand at HP and optimizing guaranteed delivery advertisment at Alibaba.

Accurate demand forecasts can increase product availability and profitability for manufacturers like HP.
We built machine learning models that outperformed existing statistical and human consensus methods at forecasting monthly demand for HP printing products.

Meanwhile, digital ad platforms like Alibaba need to predict available ad inventory and strategically allocate it to advertisers through guaranteed delivery contracts.
Our neural network model for Alibaba's ad inventory allocation also beat benchmarks on both offline and online metrics while preventing overselling.

In both cases, AI and deep learning techniques were able to uncover insights that lead to better supply chain and inventory optimization outcomes.
I'm excited to continue developing these models and potentially work on other complex business prediction problems in the future.

Sincere thanks to Prof Charles for encouraging and helping through both the projects.

Slides:

[BA Forum - Slides - PDF](/docs/ba_forum_2023.pdf)
