---
title: Rules for Life
subtitle: Constants, not variables
summary: Constants, not variables
author: Harshvardhan
date: '2022-02-18'
slug: rules
categories:
  - thoughts
  - life
  - live
tags: []
---

1.  If it takes less than 2 mins to do, do it now. The mental overhead to remember is more than the inconvenience to do it now.
2.  Do things, tell people.[^1]
3.  Build a model of everything. The model doesn't have to be perfect but just better than a coin toss. Absorb the fact that you could be 100% wrong.[^2]4. Choose what to believe in. There are good ideas in bad people's brain; bad ideas in good people brain. As Gandhi said, *hate the sin not the sinner*.
4.  Become the best in the world at what you do. Keep redefining what you do until this is true. That is: don't be the best; be the only.
5.  Work as hard as you can. Even though who you work with and what you work on are more important than how hard you work.
6.  Always demand a deadline. A deadline weeds out the extraneous and the ordinary. It prevents you from trying to make it perfect, so you have to make it different. Different is better.[^3]
7.  Promptness is a sign of respect.
8.  Never leave an empty water bottle. Fill it up when it's near-empty.
9.  **Medium is not as important as the content.**
10. Experiments are usually easier than creating theories. Prove it to yourself.
11. If you can't decide, the answer is no.
12. Do things that your future self will thank you for.

[^1]: Read on: <http://carl.flax.ie/dothingstellpeople.html>

[^2]: Darwin writes in his autobiography that he found it necessary to write down every piece of evidence which appeared to contradict his beliefs because otherwise they would disappear from his mind. When you find apparent flaws you've got to be sensitive and keep track of those things, and keep an eye out for how they can be explained or how the theory can be changed to fit them.

[^3]: Read on: <https://kk.org/thetechnium/68-bits-of-unsolicited-advice/>

------------------------------------------------------------------------

*This is a live blog and is expected to be updated frequently.*
