---
title: 'Rediscovering Coffee: A Newfound Hobby'
subtitle: "How did I found a new hobby of making coffee and surprising everyone with my methods? By making bad coffee."
summary: "How did I found a new hobby of making coffee and surprising everyone with my methods? By making bad coffee."
author: Harshvardhan
date: '2022-09-09'
slug: rediscovering-coffee
categories:
  - coffee
  - life
  - thoughts
tags: []
---

The allure of coffee has always been a constant in my life, somewhat like a well-worn book that continually unveils new chapters. I've not been a fan of Chai (चाय) like most Indians. But the rich aroma of South Indian filter coffee holds a special place in my heart, brewed traditionally and delivering a strong, aromatic decoction. During the pandemic, I also had a short fling with [Dalgona coffee](https://www.youtube.com/watch?v=9SjCEOWd3PU).

This summer, [Dea](https://deabardhoshi.medium.com/) added a refreshing twist to my coffee narrative. We ventured through the cafes of Portland, tasting various brews and inviting a whole new spectrum of flavors into my coffee experience. Initially, I struggled to discern the distinctive tastes of different coffees. However, gradually, I found myself identifying the subtle bitterness of light roasts and the rich, chocolatey nuances of dark roasts.

It became apparent to me that coffee possesses an underestimated complexity. For instance, the difference between coffee blends and single-origin variants. Blends, although budget-friendly, often compromise taste, a fact evident in the offerings of most cafes, including giants like Starbucks. Yet, in a taste showdown, the robust flavors of single-origin coffee tend to prevail.

Intrigued by this depth, I found myself yearning to delve deeper, brewing my own gourmet coffee. And when I mention "coffee", it's lattes that I favor over espresso. While this choice might limit my café exploration, it certainly does not curb the joy of my journey.

Taking Dea's advice, I subscribed to [Trade Coffee](https://www.drinktrade.com/). This service delivers a new pack of coffee every few weeks, perfectly timed with my last pack's completion. I rate each coffee I taste, helping them refine their selection and tailor their recommendations to my liking.

I've expanded my brewing repertoire with a Moka pot and a Bodum Milk frother, on the suggestion of [James Hoffman](https://www.youtube.com/watch?v=ZgIVfU0xBjA). These additions have only enhanced my brewing experience at home.

So here I am, penning down my coffee experiences, finding a renewed appreciation for the intricate world of coffee. This journey, far from over, has deepened my relationship with this beloved beverage.

Here's to many more cups, to endless discoveries, and to the simple joy that a well-brewed cup brings! ☕
